IntegerWebApplication/Models/Car.cs
using System.ComponentModel.DataAnnotations;

namespace IntegerWebApplication.Models
{
    public class Car
    {
        public int IdRegistration { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public string Varian { get; set; }

    }
}

IntegerWebApplication/Models/ErrorViewModel.cs
namespace IntegerWebApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

IntegerWebApplication/Models/Student.cs
namespace IntegerWebApplication.Models
{
    public class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string PhoneNumber { get; set;}
    }
}

IntegerWebApplication/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using IntegerWebApplication.Models;

namespace IntegerWebApplication.Controllers
{
    public class CarController : Controller
    {
        public IActionResult Index()
        {
            //var cars = new List<Car>();

           /* cars.Add(new Car()
            {
                IdRegistration = 1,
                Type = "Sedan",
                Brand = "Toyota",
                Varian = "FT86"
            });

            cars.Add(new Car()
            {
                IdRegistration = 2,
                Type = "SUV",
                Brand = "Toyota",
                Varian = "RAv4"
            });

            cars.Add(new Car()
            {
                IdRegistration = 3,
                Type = "Sedan",
                Brand = "Honda",
                Varian = "Accord"
            });

            cars.Add(new Car()
            {
                IdRegistration = 4,
                Type = "SUV",
                Brand = "Honda",
                Varian = "CRV"
            });

            cars.Add(new Car()
            {
                IdRegistration = 5,
                Type = "Sedan",
                Brand = "Honda",
                Varian = "City"
            });*/
          
            var cars = new Car[]{
            new Car{IdRegistration = 0001, Type = "Sedan", Brand = "Toyota", Varian = "FT86"},
            new Car{IdRegistration = 0002, Type = "SUV", Brand = "Toyota", Varian = "RAV4"},
            new Car{IdRegistration = 0003, Type = "Sedan", Brand = "Honda", Varian = "Accord"},
            new Car{IdRegistration = 0004, Type = "SUV", Brand = "Honda", Varian = "CRV"},
            new Car{IdRegistration = 0005, Type = "Sedan", Brand = "Honda", Varian = "City"},
            };




            //var search = cars.Single(x => x.IdRegistration == 2);
            //cars.Remove(search);

            //No 1
            /*            var tampil = cars.Where(x => x.Brand == "Honda").FirstOrDefault();
                        ViewBag.Cars = new List<Car>() { tampil};*/

            //No 2
            /*var tampil2 = cars.Where(x => x.Brand == "Honda" && x.Type == "Sedan");
            ViewBag.Cars = tampil2;
*/
            //3
            /*var tampil3 = cars.Where(x => x.Brand == "Honda" && x.Varian == "City");
            ViewBag.Cars = tampil3;
*/
            //4
            /*var tampil4 = cars.Where(x => x.Brand == "Toyota");
            ViewBag.Cars = tampil4;
*/
            //5
            /*var tampil5 = cars.Where(x => x.Varian == "City");
            ViewBag.Cars = tampil5;
*/
            //6
            var tampil6 = cars.Where(x => x.Brand == "Toyota" || x.Varian == "CRV");
            ViewBag.Cars = tampil6;


            return View();

        }
    }
}

IntegerWebApplication/Controllers/HomeController.cs
using IntegerWebApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace IntegerWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IntegerWebApplication/Controllers/StudentController.cs
using IntegerWebApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata.Ecma335;

namespace IntegerWebApplication.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {
            var student = new List<Student>();            
            student.Add(new Student()
            {
                Id = 1,
                Name = "Eling",
                Adress = "Banyumas",
                PhoneNumber = "089545567232"
            });

            student.Add(new Student()
            {
                Id = 2,
                Name = "Gilar",
                Adress = "Solo",
                PhoneNumber = "087756643432"
            });

            return View(student);
        }
    }
}

IntegerWebApplication/Views/Car/Index.cshtml
@{
    ViewData["Title"] = "Car Page";
}

<div class = "card shadow p-2">
    <h1> @ViewData["Title"]</h1>

    <table class="table-bordered table table-striped">
        <thead>
            <tr>
                <th>ID Registration</th>
                <th>Type</th>
                <th>Brand</th>
                <th>Varian</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in ViewBag.Cars)
            {
                <tr>
                    <td>@item.IdRegistration</td>
                    <td>@item.Type</td>
                    <td>@item.Brand</td>
                    <td>@item.Varian</td>
                </tr>
            }
        </tbody>
    </table>

   @*@foreach(var item in ViewBag.Cars)
    {
        <p> ID Registration : @item.IdRegistration</p>
        <p> Type : @item.Type</p>
        <p> Brand : @item.Brand</p>
        <p> Varian : @item.Varian</p>
        <hr/>
    }*@
</div>

IntegerWebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    <a href="Student/Index">Open Student By Href</a> <br/>
    <a asp-controller="Student" asp-action="Index">Open Student By ASP</a>
</div>

IntegerWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IntegerWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IntegerWebApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IntegerWebApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index">Car</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - IntegerWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IntegerWebApplication/Views/Student/Index.cshtml
@model Student;

<p>My Name Is Hendra</p>

<p> Id : @Model.Id</p>
<p> Name : @Model.Name</p>
<p> Adress : @Model.Adress</p>
<p> Phone Number : @Model.PhoneNumber</p>